info:
  name: Move to new or child for task
  type: http
  seq: 10

http:
  method: PATCH
  url: "{{base_url}}{{prefix}}"
  body:
    type: json
    data: |-
      {
        "action": "move",
        "taskId": 3,
        "parentId": 2
      }
  auth: inherit

runtime:
  variables:
    - name: page
      value: "1"
    - name: limit
      value: "20"
    - name: sortBy
      value: desc
    - name: status
      value: pending
    - name: status
      value: in_progress
    - name: priority
      value: high
    - name: search
      value: sprint

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
