name: local
variables:
  - name: base_url
    value: http://27.223.82.66:18080/api
  - secret: true
    name: token
  - secret: true
    name: refresh_token
  - name: task_id
    value: 464887c7-da95-43e4-8e40-e3c96d8739ba
  - name: action_id
    value:
      type: number
      data: "1"
