name: local
variables:
  - name: base_url
    value: http://27.223.82.66:18080/api
  - secret: true
    name: token
  - secret: true
    name: refresh_token
  - name: task_id
    value: 70c22fa0-0bba-4927-97dd-1e125a855f9b
