info:
  name: edit comment
  type: http
  seq: 4

http:
  method: PATCH
  url: "{{base_url}}{{prefix}}nested/"
  body:
    type: json
    data: |-
      {
        "action": "edit_comment",
        "taskId": 3,
        "commentId": 1,
        "text": "Updated: agenda is finalized."
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
